name: Deploy to Docker Hub

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: build/deploy the image
        run: |
          docker buildx build --push \
            --tag csandman/audiowaveform:latest \
            --tag csandman/audiowaveform:${{ github.event.release.tag_name }} \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .